### ISSUE TITLE
Server socket fd and fd limit

### ISSUE THREAD

**Issue by sysfatal** [0xjet/minb#2]
https://github.com/0xjet/minb/blob/44ca35556e4e8f84e810e9e33b1f1d61e43146bc/minb.c#L79

**Comment by sysfatal** [comment]
The server socket should not be closed. Also, the fd limit is not initialized, right?  
 
        /*
         * Close all open file descriptors except the socket
         */
        if (getrlimit(RLIMIT_NOFILE, &rl) < 0)
                die("Error: could not get limit");
        if (rl.rlim_max == RLIM_INFINITY)
                rl.rlim_max = 1024;
        for (i = 0; i < rl.rlim_max; i++)
               if(i != server_sockfd)
	       		close(i);

**Comment by 0xjet** [comment]
Thanks! Missed the getrlimit() call in a careless copy-and-paste. Moved the socket open below since there's no need for it to happen that early.
